### ISSUE TITLE
Collections score cards class missing in .net API

### ISSUE THREAD

**Issue by alsolodkin** [proknow/proknow-sdk-dotnet#55]
The python API contains a class for handling score cards within a collection 

classproknow.Collections.CollectionScorecards(collections, collection)

this class does not exist in the .net API. Can the .net API be extended to include this class.

**Comment by Jennifer-Markham** [comment]
I have created a user story for this request.

**Comment by Jennifer-Markham** [comment]
I have created a user story for this request.
